### ISSUE TITLE
S6a RA: Support for S6a Notify Request/Answer

### ISSUE THREAD

**Issue by richardgood** [RestComm/jain-slee.diameter#10]
Hi

There is a missing declaration in org.mobicents.slee.resource.diameter.s6a.EventIdCacha.java to properly support S6a Notify request/answer messages.

Attached is the diff for this to work properly.

[S6a_NOR_support.txt](https://github.com/RestComm/jain-slee.diameter/files/325147/S6a_NOR_support.txt)

Regards
Richard.

**Comment by deruelle** [comment]
@richardgood Thanks for the contribution. Can you do a pull request instead so it keeps the commit history and your name ? 
thanks in advance

**Comment by deruelle** [comment]
@brainslog can you review as well ?

**Comment by richardgood** [comment]
Hi

Sorry for delayed response - I'm using an older version so need to download
the latest to do a git pull.

I will get on this as soon as I get a chance.

Regards

**Comment by deruelle** [comment]
Thanks @richardgood . Looking forward to it.

**Comment by deruelle** [comment]
Hi @richardgood just checking if by any chance you were able to move forward on this ?

**Comment by richardgood** [comment]
Apologies, will get on this before the end of the day.

Richard.

**Comment by richardgood** [comment]
Pull request created for this minor fix - apologies for the delay.

https://github.com/RestComm/jain-slee.diameter/pull/14
