### ISSUE TITLE
Operator specific Trigger-Type Ro interface AVP value

### ISSUE THREAD

**Issue by gfigiel** [RestComm/jain-slee.diameter#21]
Hello,
We have implemented extensions to diameter Ro RA. In scope of the project we implemented additional (non-standard) value for Trigger-Type AVP. 
The value is 999 (new emum created) and causes diameter session to be served in degraded mode.

We agreed our Customer to contribute this extension so the question is to community now... Shall we include non-standard extensions to current diameter implementation?

**Comment by gfigiel** [comment]
Hello, 
Please see the PR for this issue. I believe there is no much backward compatibility issue risk. 
The only issue I can see is in scenario when some peer will generate the same, erronous AVP value by conicidence and it will be wrongly accepted by stack (customized) instead of raise an Exception.

**Comment by deruelle** [comment]
Closed from https://github.com/RestComm/jain-slee.diameter/pull/22
