### ISSUE TITLE
release-wildfly compile fails due to pom typo

### ISSUE THREAD

**Issue by richardgood** [RestComm/jain-slee.diameter#28]
In restcomm-slee-ra-diameter-base-ra-release.pom.xml there is a typo that causes compiliation failure when building the release-wildfly profile.  "tofile" should be used instead of "todir".  See below.  This should be fixed in all Diameter resource release pom.xml.

```
- <copy overwrite="true" file="${basedir}/build-wildfly.xml" todir="${release.dir}/resources/diameter-base/build.xml">
+ <copy overwrite="true" file="${basedir}/build-wildfly.xml" tofile="${release.dir}/resources/diameter-base/build.xml">

```

**Comment by SergeyLee** [comment]
Thanks @richardgood!
